### ISSUE TITLE
Still up-to-date ?

### ISSUE THREAD

**Issue by Yamakasi** [cavaliercoder/puppet-zabbix#1]
Hi,

This puppet module is one that finally looks clean, is it still up-to-date enough ?

Thanks

**Comment by cavaliercoder** [comment]
Thanks, that's why I created this one. Last update was for Zabbix 3.2.0. Stable release is up to 3.2.3. Unless Zabbix made breaking changes, it should install the latest version if you set:
```puppet
class { '::zabbix::globals' :
  version => '3.2.3',
}
```

**Comment by cavaliercoder** [comment]
FYI I just need more testing and documentation before I was going to release on the forge but this project is pretty low on my priority list. PRs warmly welcomed.

**Comment by Yamakasi** [comment]
Thanks for your update, I will check it out and report if I will use it and find something usefull!
